#!/bin/env python2 

import argparse 

from lib.config import Config 

from lib.ipa import Ipa 

  

class Main(): 

  

    def __init__(self): 

        self.args = parseArgs() 

        self.cfg = Config(self.args.config).config 

        self.ipa = Ipa(self.cfg) 

  

        for host in self.ipa.findHosts(): 

            fqdn = host['fqdn'][0] 

            self.ipa.createStandardGroups(fqdn) 

            self.ipa.createStandardHBAC(fqdn) 

            self.ipa.createStandardSudo(fqdn) 

  

  

#Standard script stuff to get args 

def parseArgs(): 

    parser = argparse.ArgumentParser() 

    parser.add_argument('-v', '--verbose', action='store_true', help='Add Debug flags') 

    parser.add_argument('--config', type=str, 

                        help='configfile to load') 

    return parser.parse_args() 

  

# Standard boilerplate to call the main() function to begin 

# the program. 

if __name__ == '__main__': Main() 
